[server]
runOnSave = true
headless = true
fileWatcherType = "poll"
folderWatchList = ["app"]
enableStaticServing = true
[browser]
gatherUsageStats = false
[logger]
level = "info"
[client]
showSidebarNavigation = false
[ui]
hideTopBar = true
